global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # Monitoreo de la aplicaci√≥n Spring Boot
  - job_name: 'inventory-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:8080']
    scrape_timeout: 5s

  # Monitoreo de PostgreSQL
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Auto-monitoreo de Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']